export const AuthRoutes ={
    register: '/register',
    login: '/',
}
export const AuthenticatedRoutes ={
    dashboard: '/',
    verifiedSalesApproval: '/verifiedSalesApproval',
    pendingSalesApproval: '/pendingSalesApproval',
    rejectSalesApproval: '/rejectSalesApproval',
    notificationAndAlert: '/notificationAndAlert',
    sellerVerificationDetailPage: '/sellerVerificationDetailPage',
    customerReviews: '/customerReviews',
    pendingApprovalProduct: '/pendingApprovalProduct',
    productDetails: '/productDetails',
    addNewCategory: '/addNewCategory',
    editAndAddProduct: '/editAndAddProduct',
    chatSupport: '/chatSupport',
    customerEnquiry: '/customerEnquiry',
    responseTicket: '/responseTicket',
    createTicket: '/createTicket',

    
    addAndManageFaqs: '/addAndManageFaqs',
    plateformTermAndCondition: '/plateformTermAndCondition',
    BannerManagementList: '/BannerManagementList',
    bannerSetting: '/bannerSetting',
    bannerSettingEdit: '/bannerSettingEdit',
    viewSingleBanner: '/viewSingleBanner',
    raiderVerification: '/raiderVerification',
    raiderLists: '/raiderLists',
    raiderDetails: '/raiderDetails',
    allOrderProductList: '/allOrderProductList',
    orderDetails: '/orderDetails',
    manageCommissionRate: '/manageCommissionRate',
}