export const SpecificationsArray = [
    { key: 'colorName', label: 'Color' },
    { key: 'ram', label: 'RAM' },
    { key: 'storage', label: 'Storage' },
    { key: 'screenSize', label: 'Screen Size' },
    { key: 'operatingSystem', label: 'Operating System' },
    { key: 'batteryCapacity', label: 'Battery Capacity' },
    { key: 'displayType', label: 'Display Type' },
    { key: 'frontCamera', label: 'Front Camera' },
    { key: 'mainCamera', label: 'Main Camera' },
    { key: 'simType', label: 'SIM Type' },
    { key: 'browseType', label: 'Browse Type' },
    { key: 'mobileOS', label: 'Mobile OS' },
    { key: 'expandableStorage', label: 'Expandable Storage' },
    { key: 'networkType', label: 'Network Type' },
    { key: 'processorType', label: 'Processor Type' },
    { key: 'storageType', label: 'Storage Type' },
    { key: 'weight', label: 'Weight' },
    { key: 'cameraType', label: 'Camera Type' },
    { key: 'lensType', label: 'Lens Type' },
    { key: 'opticalZoom', label: 'Optical Zoom' },
    { key: 'resolution', label: 'Resolution' },
    { key: 'energyRating', label: 'Energy Rating' },
    { key: 'powerConsumption', label: 'Power Consumption' },
    { key: 'capacity', label: 'Capacity' },
    { key: 'clothMaterial', label: 'Cloth Material' },
    { key: 'patternType', label: 'Pattern Type' },
    { key: 'sleeveType', label: 'Sleeve Type' },
    { key: 'neckType', label: 'Neck Type' },
    { key: 'size', label: 'Size' },
    { key: 'ageGroup', label: 'Age Group' },
    { key: 'footwearMaterial', label: 'Footwear Material' },
    { key: 'heelType', label: 'Heel Type' },
    { key: 'jewelryMaterial', label: 'Jewelry Material' },
    { key: 'gemstone', label: 'Gemstone' },
    { key: 'purity', label: 'Purity' },
    { key: 'material', label: 'Material' },
    { key: 'dimensions', label: 'Dimensions' },
    { key: 'bulbType', label: 'Bulb Type' },
    { key: 'skinType', label: 'Skin Type' },
    { key: 'ingredients', label: 'Ingredients' },
    { key: 'usage', label: 'Usage' },
    { key: 'volume', label: 'Volume' },
    { key: 'hairType', label: 'Hair Type' },
    { key: 'shade', label: 'Shade' },
    { key: 'bookTitle', label: 'Book Title' },
    { key: 'author', label: 'Author' },
    { key: 'publisher', label: 'Publisher' },
    { key: 'genre', label: 'Genre' },
    { key: 'isbn', label: 'ISBN' },
    { key: 'language', label: 'Language' },
    { key: 'pages', label: 'Pages' },
    { key: 'edition', label: 'Edition' },
    { key: 'fileFormat', label: 'File Format' },
    { key: 'artist', label: 'Artist' },
    { key: 'musicFormat', label: 'Music Format' },
    { key: 'label', label: 'Label' },
    { key: 'cast', label: 'Cast' },
    { key: 'videoFormat', label: 'Video Format' },
    { key: 'director', label: 'Director' },
    { key: 'releaseDate', label: 'Release Date' },
    { key: 'expireDate', label: 'Expire Date' },
    { key: 'batteryRequired', label: 'Battery Required' },
    { key: 'touchscreen', label: 'Touchscreen' },
    { key: 'assemblyRequired', label: 'Assembly Required' },
    { key: 'microwaveSafe', label: 'Microwave Safe' },
    { key: 'dishwasherSafe', label: 'Dishwasher Safe' },
    { key: 'smartTv', label: 'Smart TV' },
    { key: 'wired', label: 'Wired' },
    { key: 'waterResistance', label: 'Water Resistance' },
    { key: 'hybridSimSlot', label: 'Hybrid SIM Slot' },
    { key: 'fastCharging', label: 'Fast Charging' },
    { key: 'otgCompatible', label: 'OTG Compatible' },
    { key: 'graphicsCard', label: 'Graphics Card' },
    { key: 'digitalZoom', label: 'Digital Zoom' },
];

export const ProductCategoryOptions = [
    { key: 'ELECTRONICS', label: 'Electronics' },
    { key: 'HOME_APPLIANCES', label: 'Home Appliances' },
    { key: 'MENS_FASHION', label: 'Men\'s Fashion' },
    { key: 'WOMENS_FASHION', label: 'Women\'s Fashion' },
    { key: 'KIDS_FASHION', label: 'Kids Fashion' },
    { key: 'MENS_FOOTWEAR', label: 'Men\'s Footwear' },
    { key: 'WOMENS_FOOTWEAR', label: 'Women\'s Footwear' },
    { key: 'ACCESSORIES', label: 'Accessories' },
    { key: 'JEWELLERY', label: 'Jewellery' },
    { key: 'FURNITURE', label: 'Furniture' },
    { key: 'HOME_DECOR', label: 'Home Decor' },
    { key: 'KITCHENWARE', label: 'Kitchenware' },
    { key: 'BEDDING', label: 'Bedding' },
    { key: 'LIGHTING', label: 'Lighting' },
    { key: 'SKINCARE_HAIRCARE', label: 'Skincare & Haircare' },
    { key: 'MAKEUP_PERSONAL_CARE', label: 'Makeup & Personal Care' },
    { key: 'HEALTH_SUPPLEMENTS', label: 'Health Supplements' },
    { key: 'SPORTS_FITNESS_EQUIPMENT', label: 'Sports & Fitness Equipment' },
    { key: 'ADVENTURE_GEARS', label: 'Adventure Gears' },
    { key: 'SPORTSWEAR', label: 'Sportswear' },
    { key: 'BOOKS_MEDIA', label: 'Books & Media' },
    { key: 'TOYS', label: 'Toys' },
    { key: 'BABY_CARE', label: 'Baby Care' },
];